### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [geobetim/BatchHeatmaps#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by geobetim** [comment]
QGIS allows you to create one heatmap at a time with no time intervals
specification.
The plugin uses QGIS core heatmaps kernel functionality and implements
extra options, our intention with the plugin is to generate a great
quantity of heatmaps automatically according to user defined time intervals
(weeks, months, halfyear, epidemiological weeks), all simply, fast and more
efficient to make user creation of large scale heatmaps more easily.
If that answer is not clear enough, could you tell us what specific QGIS
functionality you are referring that's already present in core QGIS?


Em sex., 13 de dez. de 2019 às 15:33, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
Il 17/12/19 14:12, geobetim ha scritto:
> QGIS allows you to create one heatmap at a time with no time intervals
> specification.

not quite true: with the batch mode it's easy to run the command on many
files.
how do you specify time intervals?
thanks.

-- 
Paolo Cavallini - www.faunalia.eu
QGIS.ORG Chair:
http://planet.qgis.org/planet/user/28/tag/qgis%20board/

**Comment by geobetim** [comment]
Time intervals are selected by a combobox, containing several time
intervals, the main idea of plugin is to create heatmaps separated for each
interval.
for example: if the user wants to create a heatmap for each epidemiological
week over a year, we did not find any options like this one in QGIS that
used epidomiological weeks (an important unit of time for epidemiological
control of diseases) or other specific time units.
This plugin would greatly help and facilitate heatmaps generation for less
experienced users who wants to visualize data changes in heatmaps over a
given time.

Hope we were clearer this time.
Thanks for your disposition!

Em ter., 17 de dez. de 2019 às 10:33, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
I think this can be achieved in recent versions of QGIS (3.10 I believe at least) where you can add variables to the model. May I ask you to check and see if there is still something to improve in core QGIS?
Thanks.

**Comment by geobetim** [comment]
We did not find this function in QGIS 3.10,we don't know how to get the
same results provided by our plugin simply using qgis core functionality.
What QGIS function/tool were you talking about? Maybe through process
modeler or is there another alternative to achieve these results?

Through our plugin the user can generate for example a heatmap for each
week of the year just by selecting a few combobox in the interface, select
whether to save raw or color tif images, select to use maximum or minimum
density of all heatmaps to create a default value between them,
the plugin also groups all generated heatmaps for each selected time
interval.

Such features can be very useful for inexperienced users who want to work
with data analysis and variation.

Thanks

Em ter., 17 de dez. de 2019 às 13:22, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
Exactly, Processing --> Modeller
If the same result can be achieved through a Processing Model, better publish this instead of a full plugin, for the sake of simplicity.
Sorry to bother, but preventing a function bloat is a difficult task, with many hundreds of plugins.
Thanks for understanding.

**Comment by pcav** [comment]
Could you please update me on this? DO you still think it is useful?

**Comment by geobetim** [comment]
Yes.

And we use extensively.
Very useful.

Thanks

Em seg., 17 de fev. de 2020 às 11:11, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
Did you try setting up a Processing  model for the same thing? What are the limitations of this approach?

**Comment by geobetim** [comment]
Difficult, not flexible, not customizable.
To end user is not user friendly.

Em qua, 25 de mar de 2020 às 13:57, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
Could you please elaborate? A model may be relatively difficult to write, but for the end user is just a (double) click away.
Sorry to insist, I hope you do not mind.
Cheers.

**Comment by geobetim** [comment]
In the plugin developed by us, we do operations with the csv file (for
example, converting the date in text format to date format), we configure
some parameters of the heat map based on the csv data, among other things.
We didn't find all that flexibility in the modeler.

Thanks

Em qua., 25 de mar. de 2020 às 15:04, Paolo Cavallini <
notifications@github.com> escreveu:

**Comment by pcav** [comment]
Still not 100% convinced, but I do not want to bother too much. Now published.
Thanks for sharing!

**Comment by geobetim** [comment]
Thank you

Em qua., 25 de mar. de 2020 às 15:24, Paolo Cavallini <
notifications@github.com> escreveu:
